[SciPy](https://scipy.org/) (pronounced “Sigh Pie”) is a Python-based ecosystem of open-source software for mathematics, science, and engineering. In particular, these are some of the core packages: 
* NumPy: Base N-dimensional array package
* SciPy library: Fundamental library for scientific computing
* Matplotlib: Comprehensive 2D Plotting
* IPython: Enhanced Interactive Console
* Sympy: Symbolic mathematics
* pandas: Data structures & analysis

We have already looked briefly at Matplotlib.  In this and the next few lectures we will look at NumPy, Sympy, etc., and will also introduce important concepts and techniques for numerical computation.

# Introduction to NumPY

NumPy home page - lots of good links from here
* http://www.numpy.org/

Links to tutorials
* http://cs231n.github.io/python-numpy-tutorial/
  - nice quick review of Python then nice quick intro to highlights of NumPy
  - iPython (Jupyter) notebook format 
* https://docs.scipy.org/doc/
  - https://docs.scipy.org/doc/numpy/user/quickstart.html
    - Useful for beginners and to quickly remind yourself of basics
  - https://docs.scipy.org/doc/numpy/reference/
    - The answer to your question is surely in here, but there is lots of advanced content
* http://www.tutorialspoint.com/numpy/
  - Rather detailed - perhaps best for more advanced readers or for reference?
* http://www.python-course.eu/numpy.php
  - Quite accessible (at least to begin with) but not very deep



### To use numpy import the numpy module

In [1]:
import numpy as np  # Can call it anything but np saves typing

### What is a numpy array?

A numpy array is a vector, matrix, tensor (a "matrix" with more than 2 dimensions) of values. The size of each dimension is fixed --- unlike a Python list you cannot grow a numpy array without copying.

Every value must have the same data type (floating-point number, integer, complex numbers, etc.) --- more on this later.  

The constraints of fixed dimensions and fixed data type enable great efficiency (high speed and low memory) and facilitate use of external libraries that are highly optimized.

### Making arrays

Associated with each array is
* **shape** --- a tuple that represents the size of each dimension
* **data type** --- the type of data (http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).  The default is `float_` (a 64-bit floating point number fully compatible with Python `float`).

**From existing python list or any iterable** - `array(data)`
* When making an array from a Python data structure numpy will use try to use "simplest" data type that can hold all of the data you provide

In [2]:
a = np.array([77.0,99.0], dtype=np.float32) # Setting data type
b = np.array(range(10))
c = np.array([[11,12,13.0],[21,22,23],[31,32,33],[41,42,43]])
d = np.array([1+2j,2.0+3.14j])
print(a)
print(b)
print(c)
print(d)

[77. 99.]
[0 1 2 3 4 5 6 7 8 9]
[[11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]
 [41. 42. 43.]]
[1.+2.j   2.+3.14j]


In [3]:
print(a.dtype, b.dtype, c.dtype, d.dtype) # Data type
print(a.shape, b.shape, c.shape, d.shape)

float32 int32 float64 complex128
(2,) (10,) (4, 3) (2,)


**[Aside] Numpy data types are fixed size** --- this means that Numpy integers behave differently to Python integers (a Python integer can be arbitrarily large but Numpy integers have only a fixed range).  Numpy and Python floats behave the same.

In [4]:
a = np.array([1,2], dtype=np.int64) # Force integer data type
print(a)

[1 2]


In [5]:
print(2**63 - 1)
i = 999999999999999999999999999999999999 # a really big python integer
#a[0] = i

9223372036854775807


In [6]:
i = 2**63 - 1 # The largest signed integer that can fit into 64 bits
a[0] = i
print(i, a[0])
i += 1
a[0] += 1  # Do not rely on this always producing an overflow warning 
print(i, a[0])

9223372036854775807 9223372036854775807
9223372036854775808 -9223372036854775808


C:\Users\user\AppData\Local\Temp/ipykernel_33952/736150487.py:5: RuntimeWarning: overflow encountered in longlong_scalars
  a[0] += 1  # Do not rely on this always producing an overflow warning


**From shape** and filled with data of your chosing --- this is by far the best way to make large arrays
* You can provide the data type using the keyword argument `dtype`
* Look in the documention for the many other ways to make arrays

In [ ]:
np.arange(20)

In [7]:
a = np.zeros((2,3))    # Filled with zeros
b = np.ones((5,))      # Filled with ones
c = np.full((3,2),-7.0)# Filled with value of your chosing
d = np.eye(3)          # A 3x3 identity matrix
e = np.linspace(-1,2,11) # Look at ?np.linspace 
f = np.arange(7)         # Like python range
g = np.random.random((2,5)) # Filled with random values in [0,1]
print(a)   
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[-7. -7.]
 [-7. -7.]
 [-7. -7.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[-1.  -0.7 -0.4 -0.1  0.2  0.5  0.8  1.1  1.4  1.7  2. ]
[0 1 2 3 4 5 6]
[[0.30159247 0.66155428 0.07001986 0.89028388 0.54924444]
 [0.20170941 0.74938535 0.81235031 0.90895296 0.39474039]]


`linspace` (and `logspace`) create arrays with evenly space (in log) numbers.  For `logspace`, you specify the start and ending powers (`base**start` to `base**stop`)


d = np.linspace(0, 1, 11, endpoint=False)
print(d)

In [8]:
e = np.logspace(-1, 2, 15, endpoint=True, base=10)
print(e)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


You can also initialize an array based on a function.

In [9]:
f = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
f

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
def myFun(x,y): 
    return 10*x+y

g = np.fromfunction(myFun, (5,4), dtype=int)
g

You can reshape an array using the `reshape` member function
* The data must fit exactly --- try changing the values `5` or `3` below to see the error you get when it does not fit.
* It makes a new *view* of the data --- i.e., the new and old arrays are looking at the same underlying data, which makes it convenient to do some types of indexing.

In [10]:
a = np.arange(15)
print(a)
b = np.reshape(a,(5,3))  # same as doing a.reshape((5,3))
print(a) # Demonstrate a was unchanged
print(b)
b[1,2] = 99 # Demonstrate that b and a are viewing the same underlying data
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 0  1  2  3  4 99  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4 99]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


### Acessing array data

**Accessing elements** (also called integer indexing) --- just specify the indices inside `[]` just like Python lists

In [11]:
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a)
print("a[0,0]",a[0,0])
print("a[0,1]", a[0,1])
print("a[1,0]", a[1,0])
print("a[-1,2]", a[-1,2])
b = np.linspace(4,5,5)
print("b", b)
print("b[3]", b[3])

[[0 1 2 3]
 [4 5 6 7]]
a[0,0] 0
a[0,1] 1
a[1,0] 4
a[-1,2] 6
b [4.   4.25 4.5  4.75 5.  ]
b[3] 4.75


In [12]:
print(a[1])

[4 5 6 7]


**Array elements are mutable** --- just like Python lists

In [13]:
b[2] = 99
print(b)

[ 4.    4.25 99.    4.75  5.  ]


**Accessing slices** --- `[start:stop:increment]` just like Python slices
* But unlike Python lists Numpy slices return a **view** of the data so that you can operate on it

In [14]:
a = np.array([[0,1,2,3],[4,5,6,7]])
print("a")
print(a)

print("\nslice of a")
print(a[0:2,1:4])

patch = a[0:2,1:4] 
print("\npatch")
print(patch)

patch.fill(-1) # showing that slices are mutable and are views
print("\na after filling patch")
print(a)

a[0:2,0:2] = 99 # showing that slices are mutable
print("\na after directly assigning slice")
print(a)

a[:,:] = 0 # sets all of a --- equivilent to a.fill(0)
print("\na after setting entire array")
print(a)

a
[[0 1 2 3]
 [4 5 6 7]]

slice of a
[[1 2 3]
 [5 6 7]]

patch
[[1 2 3]
 [5 6 7]]

a after filling patch
[[ 0 -1 -1 -1]
 [ 4 -1 -1 -1]]

a after directly assigning slice
[[99 99 -1 -1]
 [99 99 -1 -1]]

a after setting entire array
[[0 0 0 0]
 [0 0 0 0]]


In [16]:
t = [1,2,3,4]
s = t[2:]   # Slicing a list gives a (shallow) copy, whereas slicing a Numpy array gives a view
print(t,s)
s[:] = [99]
print(t,s)  # Note that changing s does not change the original list
t[2:] = [100] # But if we assign the slice directly we can mutate the original list
print(t,s)

[1, 2, 3, 4] [3, 4]
[1, 2, 3, 4] [99]
[1, 2, 100] [99]


**Integer array indexing** --- you can extract multiple values at a time into a new array, or operate on those values in place.


Note that integer-array indexing behaves differently from slicing in that it always returns a new copy (instead of a view) when used as a right value.

In [17]:
a = np.arange(15).reshape((5,3))
print(a)
b = a[[2,3,4],[1,2,1]] # Makes a *copy* of a[2,1], a[3,2], a[4,1] ***************************
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 7 11 13]


In [ ]:
# Demonstrate that changing b does not change A
b[2] = -1 
print(b)
print(a)

When used as a left value, integer-array indexing can be used to change multiple elements at a time.

In [18]:
a = np.arange(20).reshape((5,4))
print(a)
print(a[np.arange(3),[0,2,3]])
a[np.arange(3),[0,2,3]] = -1
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 0  6 11]
[[-1  1  2  3]
 [ 4  5 -1  7]
 [ 8  9 10 -1]
 [12 13 14 15]
 [16 17 18 19]]


A more complicated example:

In [19]:
a = np.arange(20).reshape((5,4))
print("A")
print(a)
print("A ")
print(a[np.arange(3),[0,2,3]])
print(a[[0,1,2],[0,2,3]])
print(a[0,0], a[1,2], a[2,3])
a[np.arange(3),[0,2,3]] = -1
print(a)
a[[0,1,2],[0,2,3]] = -2
print(a)
b = a[[0,1,2],[0,2,3]] # The act of assigning returns a copy
b.fill(-99)

A
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
A 
[ 0  6 11]
[ 0  6 11]
0 6 11
[[-1  1  2  3]
 [ 4  5 -1  7]
 [ 8  9 10 -1]
 [12 13 14 15]
 [16 17 18 19]]
[[-2  1  2  3]
 [ 4  5 -2  7]
 [ 8  9 10 -2]
 [12 13 14 15]
 [16 17 18 19]]


**Mixing element-wise and slice-wise indexing** --- can be used to produce lower rank values

Combining integer-array indexing with slicing is more complicated, but it also makes a new copy.

In [20]:
c = a[(1,2),:]
d = a[1:3,:]
c[0,0]=-1
print(a)
d[0,0]=-1
print(a)

[[-2  1  2  3]
 [ 4  5 -2  7]
 [ 8  9 10 -2]
 [12 13 14 15]
 [16 17 18 19]]
[[-2  1  2  3]
 [-1  5 -2  7]
 [ 8  9 10 -2]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
a = np.arange(15).reshape((5,3))
print(a)
print(a[2,:]) # Vector containing the 3rd row of the matrix a
print(a[1:4,-1]) # Vector containing part of the last column of the matrix a

**Exercise:** Make a `(5,5)` random matrix and add 1 onto all elements in the 2nd and 3rd columns.

In [27]:
A = np.random.random((5, 5))
print(A)
A[:, 2:4] += 1
print(A)

[[0.75462398 0.29565339 0.77482347 0.34298358 0.36602736]
 [0.06428185 0.08602828 0.6368772  0.23775139 0.41104038]
 [0.32312944 0.39731466 0.4736665  0.5776374  0.74258146]
 [0.79742832 0.45102073 0.19403659 0.92173091 0.99495977]
 [0.44682932 0.00967116 0.04550159 0.76817797 0.59589303]]
[[0.75462398 0.29565339 1.77482347 1.34298358 0.36602736]
 [0.06428185 0.08602828 1.6368772  1.23775139 0.41104038]
 [0.32312944 0.39731466 1.4736665  1.5776374  0.74258146]
 [0.79742832 0.45102073 1.19403659 1.92173091 0.99495977]
 [0.44682932 0.00967116 1.04550159 1.76817797 0.59589303]]


**Iterating over an array**

We can iterate throug rows (i.e., over the first axis). It behaves like slicing.

In [28]:
a = np.arange(15).reshape((5,3))
for row in a:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]


In [29]:
print(a[1, 1]) # More efficient
print(a[1][1])

4
4


We can also iterate over element-by-element:

In [30]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


**Boolean array indexing** --- pick elements by value

In [36]:
a = np.random.random((3,4)) - 0.5
print(a)

[[ 0.38957767 -0.21101318 -0.3618778   0.12886489]
 [-0.15620596  0.4958656   0.17087115  0.27493408]
 [-0.34383423 -0.41737474  0.01312915  0.00864048]]


In [37]:
print(a>0)

[[ True False False  True]
 [False  True  True  True]
 [False False  True  True]]


You can ask if any or all of the array values satisfy the condition

In [38]:
print("are any entries greater than zero?", (a>0).any())
print("are all entries greater than zero?", (a>0).all())


are any entries greater than zero? True
are all entries greater than zero? False


You can view and change elements that satisfy a condition

In [39]:
print(a[a>0])

[0.38957767 0.12886489 0.4958656  0.17087115 0.27493408 0.01312915
 0.00864048]


In [40]:
a[a<0] = -1.0
print(a)

[[ 0.38957767 -1.         -1.          0.12886489]
 [-1.          0.4958656   0.17087115  0.27493408]
 [-1.         -1.          0.01312915  0.00864048]]


**Copy and deep copy:** As we've seen already Python assignment creates a shallow copy of arrays --- you end up with two names or views of the same underlying data.  Just like Python lists.

In [41]:
a = np.arange(5)
b = a
print(a)
print(b)
b[3] = 99
print(a) # No copy
print(b)

[0 1 2 3 4]
[0 1 2 3 4]
[ 0  1  2 99  4]
[ 0  1  2 99  4]


If you really want a completely new array that is a copy of the original data you must use `np.copy`

In [42]:
b = np.copy(a)
b[3]=-1
print(a)
print(b)

[ 0  1  2 99  4]
[ 0  1  2 -1  4]


**Other operations to make and combine arrays:** Stacking, repeating, tiling, concatenating --- read the docs for full details

In [43]:
a = np.arange(4)
print(a)
print(np.repeat(a,3))
print(np.tile(a,(2,3)))

[0 1 2 3]
[0 0 0 1 1 1 2 2 2 3 3 3]
[[0 1 2 3 0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3 0 1 2 3]]


**Matrix transpose:** this is such a common operation that Numpy provides an attribute to access it (in math the transpose of the matrix $A$ is often indicated as $A^T$).

The transpose of a matrix switches the rows and columns so that if $A$ is $m \times n$ with elements $a_{ij}$ then
* $A^T$ is $n \times m$, and 
* $(A^T)_{ji} = A_{ij}$

In [44]:
a = np.arange(12).reshape(4,3)
print(a)
print(a.T)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


### Array math 

We've seen lots of elementary examples already --- assigning and basic arithmetic

Most operations on arrays act **elementwise** and arrays being combined must have the same shape.

In [45]:
a = np.linspace(-1,2,5)
b = np.linspace( 3,4,5)
print(a)
print(b)
c = a+b
print(c)
d = 2*a + 5.0*b + a*b/c
print(d)

[-1.   -0.25  0.5   1.25  2.  ]
[3.   3.25 3.5  3.75 4.  ]
[2. 3. 4. 5. 6.]
[11.5        15.47916667 18.9375     22.1875     25.33333333]


For each operator there is an equivalent function if you find that more readable

In [46]:
c = a/b
d = np.divide(a,b)
print(c)
print(d)

[-0.33333333 -0.07692308  0.14285714  0.33333333  0.5       ]
[-0.33333333 -0.07692308  0.14285714  0.33333333  0.5       ]


**Mathematical functions** --- In addiiton to basic arithmetic all standard math functions are available
* http://docs.scipy.org/doc/numpy/reference/routines.math.html
* To quickly remind yourself what is available in Numpy use the `dir` function on the namespace

In [ ]:
print(np.sqrt(b))

In [ ]:
N = 1000
print(np.sum(np.arange(N)))
print(N*(N-1)//2) # exact result
print(np.max(np.arange(N)))
print(N-1) # exact result

You can also apply some of these functions along specific dimensions or axes of an array

In [ ]:
a = np.arange(10).reshape(5,2)
print(a)
print(np.sum(a))
print(np.sum(a ))
print(np.sum(a,1))

### Broadcasting 

In addition to elementwise operations that demand arrays in an operation (e.g., `a+b`) have the same shape, Numpy can promote or broadcast data to enable you to do operations with arrays that have different shapes and dimensions (https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).  

Two dimensions are compatible when
* they are equal, or
* one of them is 1

You've already seen this with a scalar value being logically promoted to an array with dimension provided by the other argument --- or as if the value was broadcast to all elements in the array.

In [47]:
a = np.linspace(0,5,11)
print(a)
a *= 5.0 # The scalar 5 behaves as if we had written a*np.full(11,5.0)
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25. ]


If you think of a scalar as an array of length 1, then we can apply the same logic to combining two arrays when in one array a dimension is 1 and in the other array it is larger --- the scalar value is broadcast across the larger  dimension (yes, I find this a bit confusing too, but it can be useful).

Let's say we have a matrix `B` and we want to multiply all elements in the first column by 1, the second column by 2, the third column by 3, and so on.

In [48]:
x = np.arange(1,5)  # The values we want to multiply by
B = np.arange(16).reshape(4,4) # The matrix we want to scale
print("x")
print(x)
print("B")
print(B)

print("\nB*x")
print(B*x) # x[i] is broadcast as if we had made the matrix a[i,j]=x[i]

A = np.zeros((4,4),dtype=np.int64)
for i in range(4):
    A[i,:] = x
print("\nB*A with A having elements of x mannually broadcast across rows")
print(B*A)

print("\nx*B") # since the * operation is elementwise order does not matter
print(x*B)


x
[1 2 3 4]
B
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

B*x
[[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]
 [12 26 42 60]]

B*A with A having elements of x mannually broadcast across rows
[[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]
 [12 26 42 60]]

x*B
[[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]
 [12 26 42 60]]


If instead of multiplying columns we wanted to multiply the rows, we would have to reshape `x` to change the direction of the broadcasting

In [ ]:
print("B*x")
print(B*x)

print("\nB*x.reshape(1,4)")
print(B*x.reshape(1,4))

print("\nB*x.reshape(4,1)")
print(B*x.reshape(4,1))

A = np.zeros((4,4),dtype=np.int64)
for i in range(4):
    A[:,i] = x
print(B*A)

print("\nB*A with A having elements of x manually broadcast down columns")
print(B*A)


**Vector and matrix products**

A common operation is computing the dot (or inner) product of two vectors

$$x.y = \sum_i x_i y_i $$

In [ ]:
x = np.random.random(10)
y = np.random.random(10)
total = 0.0
for i in range(10):
    total += x[i]*y[i]
print(total)
print(np.dot(x,y))

And similarly for matrices (matrix multiplication)

$$a_{i j} = \sum_k b_{i k} c_{k j}$$

In [ ]:
b = np.random.random((5,3))
c = np.random.random((3,2))
print(b)
print(c)
a = np.dot(b,c)
print(a)

**Lots of other numerical and mathematical tools** in Numpy (http://docs.scipy.org/doc/numpy/reference/) and the rest of SciPy.

### Why numpy?  

Lots of good reasons
* multidimensional data
* lots of powerful numerical options
* interfacing to third party packages
* working with very large data
* many numerical algorithms are hard to implement correctly and efficiently

But perhaps reason number 1 is **speed**

Look at the help on the %timeit and %%timeit magic commands (for Jupyter notebook)

In [ ]:
# time making an array containing the first 10 million integers and then summing it using numpy
%timeit -n 10 np.sum(np.arange(10000000))

In [ ]:
# The same using a Python list
%timeit -n 10 sum(list(range(10000000)))

In [ ]:
# The same again using Python skipping making the Python list
%timeit -n 10 sum(range(10000000))

### Vectorizing functions

Sometimes we need to operate on each element with some Python code but to get good performance we should try to avoid writing Python loops over elements in our vectors and matrices, and instead use vectorized algorithms where the loop is implemented by Numpy (rather than by you in Python). 

Here's a Python function that implements a step function (this is easy to do in Numpy but you can see that the function could be doing anything).

In [ ]:
def Theta(x):
    " Scalar implemenation of the Heaviside step function. "
    if x >= 0:
        return 1
    else:
        return 0
print(Theta(3.0), Theta(-1.0))

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
x = np.linspace(-3,3,49)
y = np.array([Theta(value) for value in x])
print(x)
print(y)
plt.plot(x,y);

But if we try to apply it to an array it breaks since Numpy is confused about what to do with it

In [ ]:
a = np.array([-3,-2,-1,0,1,2,3])
Theta(a)

We could write a python loop (or a list comprehension like we did in the plot), but we know this will be slow
* And it is also error prone since we have to write more code

In [ ]:
result = np.copy(a)
for i,value in enumerate(result):
    result[i] = Theta(value)
print(result)
print([Theta(value) for value in a])

The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.
* We do this with the `np.vectorize` function

In [ ]:
Theta_vectorized = np.vectorize(Theta)
print(Theta_vectorized(a))

We can also implement the function to accept a vector input from the beginning (requires more effort but will probably give better performance):

In [ ]:
def Theta_vector_aware(x):
    " Vector-aware implemenation of the Heaviside step function " 
    return 1 * (x >= 0)

Theta_vector_aware(np.array([-3,-2,-1,0,1,2,3]))

In [ ]:
# still works for scalars as well
Theta_vector_aware(-1.2), Theta_vector_aware(2.6)

Which is the fastest?

In [ ]:
N = 1000000
x = np.random.random(N) - 0.5


In [ ]:
# Python loop appending to initially empty list
result = []
%timeit -n 10 -r 1 for i in range(N): result.append(Theta(x[i]))

In [ ]:
# Python loop assigning into pre-allocated list
result = list(x)
%timeit -n 10 -r 1 for i in range(N): result[i] = Theta(x[i])

In [ ]:
# Python loop assigning into pre-allocated Numpy array
result = np.copy(x)
%timeit -n 10 -r 1 for i in range(N): result[i] = Theta(x[i])

In [ ]:
# Python list comprehension
%timeit -n 10 -r 1 result = [Theta(value) for value in x]

In [ ]:
# Vectorized Python function operating on array
%timeit -n 10 -r 1 result = Theta_vectorized(x)

In [ ]:
# Vector aware function operating on array
%timeit -n 10 Theta_vector_aware(x)

In [ ]:
# Numpy builtin step function
%timeit -n 10 np.heaviside(x,1.0)

On my laptop (while running in power save on battery) --- speed up is relative to Python append

| Version | Time(ms) | Speedup |
| :-- | :-- | :-- |
| Python list append | 582 | 1.0 |
| Python list insert | 547 | 1.06 |
| Python array insert | 670 | 0.87 |
| Python list comp.  | 452 | 1.29 |
| Vectorized Python func. | 243 | 2.40 |
| Vector aware func. | 2.35 | 248 |
| Numpy builtin | 11.4 | 51.0 |

## Algorithmic complexity (and a little more benchmarking)

Since we are talking about the time calculations take this is a good opportunity to discuss algorithmic complexity --- i.e., how long calculations take as a function of the size of the input.

If we are making adding two vectors of length `N` how do you expect the time taken to increase as we increase `N`?

The Python code is something like
```
for i in range(N):
    c[i] = a[i] + b[i]
```

How many times is the statement inside the for-loop executed?

Let's measure the time as a function of `N` using Numpy instead of native Pyhon

In [ ]:
import timeit
?timeit.Timer.timeit

In [ ]:
import timeit
times = []
Ns = []
for m in range(24):
    N = 2**m
    timer = timeit.Timer("c = a+b",
                         setup="import numpy as np; N=%d; a=np.zeros(N); b=np.zeros(N)"%(N))
    timer.timeit(number=10) # Discard the initial measurement 
    times.append(timer.timeit(number=100))
    Ns.append(N)
print(times)
print(Ns)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(Ns,times)

This is clearly linear, with this behavior dominating for large N.  Computer scientists and mathematicians would say that the cost of this computation is $O(N)$  (read as big-oh N) or **order N**.  This means that for sufficiently large $N$ the cost of the calculation is $\le C N$ for some constant $C$.  

In other words, *if we double $N$ then the cost of the calculation is doubled* because $(2N)^1 = 2 N$ (for sufficiently large $N$).

What about multiplying a vector by a matrix?
$$
y_i = \sum_j a_{i j} x_j
$$

Or in Python
```
for i in range(N):
    for j in range(N):
        y[i] += a[i,j]*x[j]
```
How many times is the statement in the inner loop executed?

Let's time it using the Numpy equivalent operation (`dot`)

In [ ]:
import timeit
times = []
Ns = []
for N in range(200,2200,200):
    timer = timeit.Timer("y = np.dot(A,x)",
                         setup="import numpy as np; N=%d; A=np.zeros((N,N)); x=np.zeros(N)"%(N))
    timer.timeit(number=10) # Discard the initial measurement 
    times.append(timer.timeit(number=4000))
    Ns.append(N)
print(times)
print(Ns)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(Ns,times)

This is a quadratic function (though noise in your times may make this hard to see --- ideally you should run this on a completely idle computer).

I.e., the cost of matrix-vector multiplication is $O(N^2)$.

In other words, *if we double $N$ then the cost of the calculation is quadrupled*  because $(2N)^2 = 4 N^2$.

What about matrix multiplication?

$$
c_{ij} = \sum_k a_{i k} b_{k j}
$$

Or in Python
```
for i in range(N):
    for j in range(N):
        for k in range(N):
            c[i,j] += a[i,k]*b[k,j]
```
How many times is the statement in the inner loop executed?

Again, let's time the Numpy equivalent

In [ ]:
import timeit
times = []
Ns = []
for N in range(200,1200,100):
    timer = timeit.Timer("C = np.dot(A,B)",
                         setup="import numpy as np; N=%d; A=np.zeros((N,N)); B=np.zeros((N,N))"%(N))
    timer.timeit(number=10) # Discard the initial measurement
    times.append(timer.timeit(number=100))
    Ns.append(N)
print(times)
print(Ns)

In [ ]:
plt.plot(Ns,times)

This is a cubic function (though noise in your times may make this hard to see --- ideally you should run this on a completely idle computer).

I.e., the cost of matrix-matrix multiplication is $O(N^3)$.

In other words, *if we double $N$ then the cost of the calculation is octupled* because $(2N)^3 = 8 N^3$.

Summary:

| Operation     |  Order    |
| ------------- | --------- |
| Vector        |  `O(N)`   |
| Matrix-vector |  `O(N**2)` |
| Matrix-matrix |  `O(N**3)` |

So you can see that some algorithms/operations can become very expensive even for apparently small $N$.

Some problems can be solved with multiple algorithms that have different algorithmic complexities which can be data dependent.  For example sorting,

| Algorithm | Worst case |
| --- | --- |
| Selection | `O(N**2)` | 
| Bubble    | `O(N**2)` | 
| Heap sort | `O(N log N)` |
| etc.      |  |



**Exercise:** Time (using either `%timeit` or `timeit.Timer`) each of the implementations of the `Theta` function applied to a vector (Python loop, vectorized Python function, native Numpy function) for vectors of length up to `2**23`.


## Further reading

Reading on NumPy:
* Chapter 2 of Numerical Python book
* http://www.numpy.org
* https://docs.scipy.org/doc/numpy/user/quickstart.html - Quickstart Tutorial for NumPy
* https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html - A Numpy guide for MATLAB users.

Reading on SciPy:
* http://www.scipy.org - The official web page for the SciPy project
* http://docs.scipy.org/doc/scipy/reference/tutorial/index.html - A tutorial on how to get started using SciPy. 
* https://github.com/scipy/scipy/ - The SciPy source code. 


## Acknowledgements

Some content adapted from J.R. Johansson's Scientific Python Lectures available at [http://github.com/jrjohansson/scientific-python-lectures](http://github.com/jrjohansson/scientific-python-lectures).